Set concrete colours for toolbar border
rafaelmardojai/firefox-gnome-theme pull request #739
Opened 2024-01-04 04:02 UTC by AbrarSL

![light](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/69783006/6e504273-8dc3-4591-9b45-ce340d52dcaa)
![dark](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/69783006/6cae8ff1-c511-42f0-b9b5-7177e595b458)

This makes it look identical to the border in GNOME Web.

2024-01-04 13:52 UTC, rafaelmardojai commented
Actually checking libadwaita we want to use the colors from `headerbar_darker_shade_color` which is set to:

```css
@define-color headerbar_darker_shade_color #{if($variant == 'light', transparentize(black, .88), transparentize(black, .1))};
```

That will be `rgba(0, 0, 0, 0.12)` for light and `rgba(0, 0, 0, 0.9)` for dark.

The coloring issue should be fixed be fixed by giving `#navigator-toolbox` a background (`--gnome-toolbar-background`).

2024-01-04 14:07 UTC, AbrarSL commented
> Actually checking libadwaita we want to use the colors from `headerbar_darker_shade_color` which is set to:
> 
> ```css
> @define-color headerbar_darker_shade_color #{if($variant == 'light', transparentize(black, .88), transparentize(black, .1))};
> ```
> 
> That will be `rgba(0, 0, 0, 0.12)` for light and `rgba(0, 0, 0, 0.9)` for dark.
> 
> The coloring issue should be fixed be fixed by giving `#navigator-toolbox` a background (`--gnome-toolbar-background`).

Is it okay now?

2024-01-04 15:25 UTC, rafaelmardojai commented
@AbrarSL Yes, but better update the `--gnome-headerbar-shade-color` var to these colors, we don't have a use case for the non darker version.

2024-01-04 15:35 UTC, AbrarSL commented
`--gnome-toolbar-background: var(--gnome-headerbar-background);` and `--gnome-toolbar-color: var(--gnome-window-color);` seems unnecessary too? Shall I just get rid of them and directly use the variables they point to?

@rafaelmardojai

2024-01-04 15:41 UTC, rafaelmardojai commented
@AbrarSL `--gnome-toolbar-background` should stay for semantics, but `--gnome-toolbar-color` can be removed since I don't think we ever will have divergence of colors there.

2024-01-04 15:55 UTC, AbrarSL commented
@rafaelmardojai Done.

2024-01-04 17:42 UTC, rafaelmardojai requested changes
Thanks! All looks good, just two minor nitpick.

2024-01-04 17:42 UTC, rafaelmardojai commented on theme/colors/dark.css
> +    --gnome-toolbar-border-color: var(--gnome-headerbar-shade-color);
It has the same value that light (`--gnome-headerbar-shade-color`) so no need to define it again here.

2024-01-04 17:42 UTC, rafaelmardojai commented on theme/colors/light.css
> +  --gnome-toolbar-border-color: var(--gnome-headerbar-shade-color);
Please use tab for indentation.

2024-01-05 00:46 UTC, rafaelmardojai approved these changes

2024-01-05 00:47 UTC, merged

2024-01-05 00:47 UTC, rafaelmardojai commented
Thanks a lot for taking the time!